modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="blocks_of_illusion"
version="1.0.0"
displayName="blocks of illusion"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Ian13, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.blocks_of_illusion]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration