modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="blocks_of_illusion"
version="0.0.1"
displayName="blocks of illusion"
displayURL="https://mcreator.net"
logoFile="logo.png"
credits="moin"
authors="Ian1337"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.blocks_of_illusion]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration